/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "esrodzhmdubdnoicecfr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzcm9kemhtZHViZG5vaWNlY2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NDM3ODksImV4cCI6MjA4NTMxOTc4OX0.YLlzxwuaSrvjC9DD9v4u9DWCTnBma8YqaWO--Tr2p6k"